FROM node:lts-stretch-slim
MAINTAINER Opstree Solutions

COPY . /app

WORKDIR /app/frontend

RUN apt-get update -y && \
    apt-get install git -y

RUN npm install && \
    npm i serve

RUN npm run build

ENTRYPOINT ["serve"]

CMD ["-s" "build"]
