FROM maven:latest as builder
MAINTAINER Opstree Solutions
COPY . /java/
WORKDIR /java/gateway
RUN mvn package

FROM alpine:latest
MAINTAINER Opstree Solutions
USER root
RUN apk update && \
    apk fetch openjdk8 && \
    apk add openjdk8
COPY --from=builder /java/gateway/target/gateway-service.jar /app/gateway.jar

ENTRYPOINT ["/usr/bin/java", "-jar", "/app/gateway.jar"]
